import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Coding Beast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.navbar}>
          <ul>
            <Link href={'/home'}> <li>Home</li> </Link>
            <Link href={'/blogs'}> <li>Blogs</li> </Link>
            <Link href={'/contact'}> <li>Contact</li> </Link>
            <Link href={'/about'}> <li>About</li> </Link>
            
          </ul>
      </nav>

      <main className={styles.main}>

        <h1 className={styles.title}>
        Welcome to Coding Beast
        </h1>

        {/* <p>
        <Image
          src="/logo.png"
          alt="Coding Beast Logo"
          width={400}
          height={400}
          priority
        />
        </p> */}

        <div className={styles.blogs}>

          <h2 >Popular Blogs</h2> 

          <div className={styles.blog}>
            <h3>How to learn JavaScript in 2023</h3>

            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, corporis?</p>

            <button className={styles.button}>Read More</button>        
          </div>

          <div className={styles.blog}>
            <h3>How to learn JavaScript in 2023</h3>

            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, corporis?</p>

            <button className={styles.button}>Read More</button>        
          </div>

          <div className={styles.blog}>
            <h3>How to learn JavaScript in 2023</h3>

            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, corporis?</p>

            <button className={styles.button}>Read More</button>        
          </div>
        </div>
     </main>  
     
    </div>
  )
}